apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: announcer
  namespace: nais
spec:
  accessPolicy:
    outbound:
      external:
        - host: nais.io
        - host: slack.com
  env:
    - name: SLACK_CHANNEL_ID
      value: "C01DE3M9YBV"
  envFrom:
    - secret: announcer
  image: {{image}}
  ingresses:
    - https://announcer.external.prod-gcp.nav.cloud.nais.io
  observability:
    logging:
      destinations:
        - id: loki
  resources:
    limits:
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 32Mi
  valkey:
    - access: readwrite
      instance: rss
